#!/bin/bash

# HACK: assume install to $HOME !!
ABI_DIR=$HOME
ABI_INC=$ABI_DIR/include
ABI_LIB=$ABI_DIR/bin

CC=gcc

${CC} -DMPI_ABI -I${ABI_INC} $* -Wl,-rpath=${ABI_LIB} -L${ABI_LIB} -lmpi_abi -lmpi
